name: Getting started with your Artillery 3D printer
title: Getting started with your Artillery 3D printer
description: Collection of resources to get new people started with 3D printers
theme: jekyll-theme-leap-day
show_downloads: false
google_analytics: UA-165446016-1